name: learningproject
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.11.0+cu128
      - torchvision==0.26.0+cu128
      - torchaudio==2.11.0+cu128
      - numpy==2.5.2
      - pillow==12.3.0
      - ipykernel==7.3.0
      - ipython==9.17.1